max_width = 160
chain_width = 60
fn_call_width = 100
struct_lit_width = 100
array_width = 100
overflow_delimited_expr = false
fn_args_layout = "Compressed"
where_single_line = true
wrap_comments = true
